name: Build, Push and Pull Docker Image

on:
  push:
    branches:
      - main

env:
  # carregando IMAGE_NAME a parti do env
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:${{ split('/', github.ref)[2] }}-${{ github.run_number }}

jobs:
  build-push-pull:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Push Docker image
        if: success()
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Pull Docker image
        if: success()
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Print image digest
        if: success()
        run: echo ${{ env.IMAGE_NAME }}@${{ github.event.outputs.digest }}
