on:
  push:
    branches: [main] # Aqui você pode definir em qual branch será feito o build e push

env:
  IMAGE_NAME: ${{ github.repository }}:main-${{ github.run_number }}
  TAG_NAME: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t eriknathan/$IMAGE_NAME .

  tag:
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Create Docker tag
        run: docker tag eriknathan/$IMAGE_NAME eriknathan/$IMAGE_NAME:$TAG_NAME

  push:
    needs: [tag]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker image
        run: docker push $IMAGE_NAME

  pull:
    needs: [push]
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image
        run: docker pull $IMAGE_NAME
