on:
  push:
    branches: [main] # Aqui você pode definir em qual branch será feito o build e push

env:
  # IMAGE_NAME: ${{ github.repository }}:main-${{ github.run_number }}
  IMAGE_NAME: ${{ github.repository }}:latest
  # TAG: ${{ github.repository }}:latest ${{ github.repository }}:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: your-image-name:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: $IMAGE_NAME

      - name: Pull Docker Image
        env:
          IMAGE_NAME: $IMAGE_NAME
        uses: docker://docker.io/library/ubuntu:latest
        with:
          args: docker pull $IMAGE_NAME
